# Configuración base (común a todos los perfiles)

# Nombre de la aplicación
spring.application.name=BakeCost

# Perfil activo por defecto
spring.profiles.active=dev

# Puerto del servidor
server.port=8080

# Configuración CORS
app.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:5173}

# ---- JPA / Hibernate ----
spring.jpa.show-sql=false

# Formato legible del SQL
spring.jpa.properties.hibernate.format_sql=true

# Dialecto PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Estrategia DDL
spring.jpa.hibernate.ddl-auto=none

# ---- Serialización JSON ----
spring.jackson.default-property-inclusion=non_null
